import type { DemoData } from "@/lib/types"

const studentImage =
  "https://images.pexels.com/photos/10614241/pexels-photo-10614241.jpeg?auto=compress&cs=tinysrgb&w=1400&q=80"
const libraryImage =
  "https://images.unsplash.com/photo-1770910236912-862918eca455?auto=format&fit=crop&w=1100&q=80"
const archiveImage =
  "https://images.unsplash.com/photo-1764529079425-2ce32cd92b8a?auto=format&fit=crop&w=900&q=80"
const fabricImage =
  "https://images.unsplash.com/photo-1726207873181-03af2636095d?auto=format&fit=crop&w=700&q=80"
const videoPoster =
  "https://images.pexels.com/videos/8716787/pexels-photo-8716787.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200"

export const demoData: DemoData = {
  publicContent: {
    hero: {
      eyebrow: "Knowledge · community · future",
      title: "A serious home for African education and shared progress.",
      lede: "A home for African education, community knowledge, and the people carrying it forward.",
      imageUrl: studentImage,
      imageAlt: "African students collaborating in a bright learning space — Unique Digitals on Pexels",
      caption: "A learning culture with a long view",
      index: "01 / 04",
    },
    featuredMessage: {
      title: "Knowledge is a shared responsibility.",
      description: "A message on building trusted knowledge together.",
      videoUrl:
        "https://videos.pexels.com/video-files/8716787/8716787-uhd_3840_2160_25fps.mp4",
      posterUrl: videoPoster,
      posterAlt: "People in a modern seminar setting — Pavel Danilyuk on Pexels",
      transcriptAvailable: true,
      publishedAt: "2026-09-04",
      durationMinutes: 8,
    },
    about: {
      eyebrow: "About AsaPhis",
      title: "A long-term home for learning and participation.",
      paragraphs: [
        "AsaPhis makes African education, community knowledge, and thoughtful participation easier to find and carry forward.",
      ],
      imageUrl: libraryImage,
      imageAlt: "Atmospheric modern library archive space — Adrien Olichon on Unsplash",
    },
    vision: {
      title: "Build the foundation before the horizon.",
      intro: "See what exists today and what comes next.",
      current: {
        title: "Current work",
        body: "Learning and community tools that are available now.",
        items: [
          "Public education previews",
          "Moderated member contribution",
          "Clear verification and support flows",
        ],
      },
      future: {
        title: "Future goals",
        body: "Long-term knowledge infrastructure built through research and collaboration.",
        items: [
          "Historical and community knowledge databases",
          "Research and collaboration tools",
          "African AI and data infrastructure",
        ],
      },
    },
    educationPreview: [
      {
        id: "public-history",
        category: "History",
        kind: "Article",
        title: "How to keep context when a story travels",
        description: "A guide to reading historical material with context.",
        imageUrl: archiveImage,
        imageAlt: "Rows of books in an archive — Sveta R on Unsplash",
        visibility: "public",
        publishedAt: "2026-09-03",
      },
      {
        id: "public-community",
        category: "Community knowledge",
        kind: "Brief",
        title: "A community note is more than a post",
        description: "What makes a community contribution ready to share.",
        imageUrl: fabricImage,
        imageAlt: "Close-up of woven African fabric — engin akyurt on Unsplash",
        visibility: "public",
        publishedAt: "2026-08-22",
      },
      {
        id: "public-technology",
        category: "Technology",
        kind: "Video",
        title: "Designing technology for people who need it",
        description: "A primer on clear, accountable digital systems.",
        imageUrl: libraryImage,
        imageAlt: "Modern library reading space — Adrien Olichon on Unsplash",
        durationMinutes: 12,
        visibility: "public",
        publishedAt: "2026-08-14",
      },
    ],
    support: {
      title: "Support keeps the foundation open.",
      body: "Contributions support education, moderation, and secure member access.",
      reasons: [
        "Keep public education previews accessible",
        "Support moderation and source review",
        "Build secure, African-focused knowledge infrastructure",
      ],
      amount: 25000,
      currency: "NGN",
      methods: ["Card", "Transfer", "Mobile money"],
    },
    communityPreview: {
      title: "Community, with care.",
      body: "Read, comment, reply, react, and submit through a visible review process.",
      imageUrl: studentImage,
      imageAlt: "Students sharing a collaborative learning moment — Unique Digitals on Pexels",
      links: [
        { label: "Join our WhatsApp community", href: "https://wa.me/2348000000000" },
        { label: "Join our Telegram community", href: "https://t.me/asaphis" },
      ],
    },
  },
  countryConfigs: {
    Nigeria: {
      country: "Nigeria",
      identityDocuments: ["NIN", "Passport", "Driver's Licence"],
      contribution: {
        currency: "NGN",
        amount: 25000,
        methods: ["Card", "Transfer", "Mobile money"],
        usesGlobalFallback: false,
      },
      phoneChannels: ["SMS", "WhatsApp", "Voice"],
    },
    Ghana: {
      country: "Ghana",
      identityDocuments: ["Ghana Card", "Passport", "Driving Licence"],
      contribution: {
        currency: "GHS",
        amount: 350,
        methods: ["Card", "Transfer", "Mobile money"],
        usesGlobalFallback: false,
      },
      phoneChannels: ["SMS", "WhatsApp", "Voice"],
    },
    Kenya: {
      country: "Kenya",
      identityDocuments: ["National ID", "Passport", "Driving Licence"],
      contribution: {
        currency: "KES",
        amount: 3200,
        methods: ["Card", "Transfer", "Mobile money"],
        usesGlobalFallback: false,
      },
      phoneChannels: ["SMS", "WhatsApp"],
    },
    "United Kingdom": {
      country: "United Kingdom",
      identityDocuments: ["Passport", "Driving Licence"],
      contribution: {
        currency: "GBP",
        amount: 20,
        methods: ["Card", "Transfer"],
        usesGlobalFallback: false,
      },
      phoneChannels: ["SMS", "Voice"],
    },
    "United States": {
      country: "United States",
      identityDocuments: ["Passport", "State ID", "Driving Licence"],
      contribution: {
        currency: "USD",
        amount: 25,
        methods: ["Card", "Transfer"],
        usesGlobalFallback: false,
      },
      phoneChannels: ["SMS", "Voice"],
    },
    "Other / support needed": {
      country: "Other / support needed",
      identityDocuments: ["Passport", "Support review"],
      contribution: {
        currency: "USD",
        amount: 25,
        methods: ["Card", "Transfer"],
        usesGlobalFallback: true,
      },
      phoneChannels: ["SMS", "Voice"],
    },
  },
  member: {
    name: "Amara Okafor",
    initials: "AO",
    memberId: "MEM-NG-240918",
    country: "Nigeria",
    joinedAt: "2026-09-08",
    identityVerified: true,
    phoneVerified: true,
    accountStatus: "active",
  },
  resources: [
    {
      id: "resource-1",
      category: "History",
      kind: "Article",
      title: "Reading the archive with context",
      description: "A guide to primary sources and perspective.",
      imageUrl: archiveImage,
      imageAlt: "Tall archive bookshelves — Jameson Berrios on Unsplash",
      visibility: "member",
      publishedAt: "2026-09-06",
    },
    {
      id: "resource-2",
      category: "Culture",
      kind: "Video",
      title: "Material memory: what craft carries",
      description: "A conversation about materials, patterns, and place.",
      imageUrl: fabricImage,
      imageAlt: "Close-up of woven textile pattern — engin akyurt on Unsplash",
      durationMinutes: 18,
      visibility: "member",
      publishedAt: "2026-09-01",
    },
    {
      id: "resource-3",
      category: "Technology",
      kind: "Brief",
      title: "Building better digital public goods",
      description: "A brief on useful, accountable infrastructure.",
      imageUrl: libraryImage,
      imageAlt: "Modern library and archive interior — Adrien Olichon on Unsplash",
      visibility: "member",
      publishedAt: "2026-08-26",
    },
    {
      id: "resource-4",
      category: "Community knowledge",
      kind: "Article",
      title: "From note to shared knowledge",
      description: "How to submit a contribution with context and sources.",
      imageUrl: studentImage,
      imageAlt: "African students collaborating — Unique Digitals on Pexels",
      visibility: "member",
      publishedAt: "2026-08-18",
    },
    {
      id: "resource-5",
      category: "Development",
      kind: "Document",
      title: "Questions for a more useful future",
      description: "A brief on education, work, and collective agency.",
      imageUrl: libraryImage,
      imageAlt: "Light-filled library shelves — Adrien Olichon on Unsplash",
      visibility: "member",
      publishedAt: "2026-07-21",
    },
  ],
  documents: [
    {
      id: "doc-1",
      title: "Member contribution guide",
      description: "How to submit a sourced community note.",
      category: "Community knowledge",
      publishedAt: "2026-09-07",
      fileType: "PDF",
      authorization: "allowed",
    },
    {
      id: "doc-2",
      title: "Education collection brief",
      description: "A short orientation to the learning library.",
      category: "Education",
      publishedAt: "2026-08-29",
      fileType: "PDF",
      authorization: "allowed",
    },
    {
      id: "doc-3",
      title: "Research partnership outline",
      description: "An early working document for approved collaborators.",
      category: "Development",
      publishedAt: "2026-07-12",
      fileType: "DOCX",
      authorization: "denied",
    },
  ],
  submissions: [
    {
      id: "submission-1",
      title: "A note on neighborhood learning circles",
      body: "A draft contribution about how informal study groups share resources and keep learning visible.",
      status: "Changes Requested",
      adminMessage: "Please provide a source or first-person context for this information before resubmitting.",
      updatedAt: "2026-09-08",
    },
  ],
  notifications: [
    {
      id: "notification-1",
      category: "Account",
      title: "Your contribution was approved.",
      body: "Your initial membership contribution is recorded and your account is active.",
      createdAt: "2026-09-08",
      read: false,
    },
    {
      id: "notification-2",
      category: "Education",
      title: "New AsaPhis video available.",
      body: "Material memory: what craft carries is now ready in Education.",
      createdAt: "2026-09-07",
      read: false,
    },
    {
      id: "notification-3",
      category: "Moderation",
      title: "Your submission needs changes.",
      body: "A moderator requested a source before the contribution can move forward.",
      createdAt: "2026-09-06",
      read: true,
    },
    {
      id: "notification-4",
      category: "Security",
      title: "New login detected.",
      body: "Chrome on macOS · Lagos, Nigeria. Review Security if this was not you.",
      createdAt: "2026-09-05",
      read: true,
    },
    {
      id: "notification-5",
      category: "Travel",
      title: "Travel access request saved.",
      body: "Your request remains pending review.",
      createdAt: "2026-09-02",
      read: true,
    },
  ],
  travelRequests: [
    {
      id: "travel-1",
      destination: "United Kingdom",
      startDate: "2026-08-01",
      endDate: "2026-08-21",
      reason: "Research visit",
      status: "Expired",
      expiresAt: "2026-08-21",
    },
    {
      id: "travel-2",
      destination: "Ghana",
      startDate: "2026-10-01",
      endDate: "2026-10-21",
      reason: "Partner workshop",
      status: "Pending",
    },
  ],
  supportRequests: [
    {
      id: "SUP-260918",
      category: "Security",
      subject: "Trusted device question",
      message: "I need help understanding my current sessions.",
      status: "pending",
      createdAt: "2026-09-08",
      responses: [
        {
          author: "AsaPhis Member Care",
          body: "We have your request and will respond here within two days.",
          createdAt: "2026-09-08",
        },
      ],
    },
  ],
}
