export default () => ({
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  PORT: Number(process.env.PORT ?? 4000),
  API_PREFIX: process.env.API_PREFIX ?? 'api/v1',
  USER_WEB_URL: process.env.USER_WEB_URL ?? 'http://localhost:3000',
  ADMIN_WEB_URL: process.env.ADMIN_WEB_URL ?? 'http://localhost:3001',
  DATABASE_URL: process.env.DATABASE_URL ?? '',
  REDIS_URL: process.env.REDIS_URL ?? 'redis://localhost:6379',
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET ?? 'dev-access-secret-change-me-32chars',
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET ?? 'dev-refresh-secret-change-me-32chars',
  JWT_ACCESS_TTL: Number(process.env.JWT_ACCESS_TTL ?? 900),
  JWT_REFRESH_TTL: Number(process.env.JWT_REFRESH_TTL ?? 2592000),
  COOKIE_SECURE: (process.env.COOKIE_SECURE ?? 'false') === 'true',
  PHONE_PRIMARY_PROVIDER: process.env.PHONE_PRIMARY_PROVIDER ?? 'mock',
  PHONE_FALLBACK_PROVIDER: process.env.PHONE_FALLBACK_PROVIDER ?? 'mock',
  IDENTITY_PRIMARY_PROVIDER: process.env.IDENTITY_PRIMARY_PROVIDER ?? 'mock',
  AFRICA_ONLY_MEMBERS: (process.env.AFRICA_ONLY_MEMBERS ?? 'false') === 'true',
  S3_BUCKET: process.env.S3_BUCKET ?? 'asaphis-media',
  S3_REGION: process.env.S3_REGION ?? 'eu-west-1',
});
